### get all users
GET http://localhost:8080/users

### get profile address
GET http://localhost:8080/users/1

###
GET http://localhost:8080/users/all

###
GET http://localhost:8080/users/all?sortby=email

###
POST http://localhost:8080/users/register
Content-Type: application/json

{
    "name":  "Najnin Ahmed",
    "email": "najnin-ahmed@sn-tech.com",
    "password": "najnin-pass"
}

###
PUT http://localhost:8080/users/3/name
Content-Type: application/json

{
  "name":  "Najnin Islam"
}

###
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Updated Name",
  "email": "updated.email@example.com"
}

###
DELETE http://localhost:8080/users/1

### get all deleted users
GET http://localhost:8080/users/deleted